flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- aeson-0.11.3.0
- load-env-0.1.1
- authenticate-oauth-1.5.1.2
- hoauth2-0.5.4.0
- http-client-0.4.31.2
- http-client-tls-0.2.4.1
- http-conduit-2.1.11
- yesod-auth-oauth-1.4.1.1
- yesod-auth-oauth2-0.2.2
resolver: nightly-2017-02-06
